- name: play1
  hosts: local
  become: true
  vars_files:
    - vars_method5.yml

  tasks:
    - name: Install package
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present
